### PR TITLE
Fixed modelCheckLib with selftests

### PR DESCRIPTION
**Pull request by binghe**
modelCheckLib only works with HOL built by Moscow ML, I've fixed it and confirmed that it works now.

### CODE REVIEW

**Comment by thtuerk** [comment]
thanks

**Comment by binghe** [comment]
Hi Thomas,

could you please document a little on the API in the `modelCheckLib`?  For example, what's the meaning of `model_check___ltl_equivalent_initial` and `model_check___ltl_equivalent`, and their differences?

Regards,

Chun

**Comment by binghe** [comment]
Sorry, by looking at the following definitions now the meaning of those API functions is clear enough to me:

```
val LTL_EQUIVALENT_def =
 Define
   `LTL_EQUIVALENT b1 b2 = !t w. (LTL_SEM_TIME t w b1) = (LTL_SEM_TIME t w b2)`;

val LTL_EQUIVALENT_INITIAL_def =
 Define
   `LTL_EQUIVALENT_INITIAL b1 b2 = !w. (LTL_SEM w b1) = (LTL_SEM w b2)`;
```

No more questions:)

**Comment by thtuerk** [comment]
My reply by email got swalled by github apparently. Anyhow, here it is again:

It's 12 years since I did this example. I don't have a clue what it does any more except what is already documented.

> (* Checks that the given ltl-formulas are equivalent at the first point of time. Since there are past ltl operators this does not mean that they are equivalent for all points of time!*)
> val model_check___ltl_equivalent_initial : Abbrev.term -> Abbrev.term -> Abbrev.thm option
>
> (* Checks that the given ltl-formulas are equivalent at all points of time.*)
> val model_check___ltl_equivalent : Abbrev.term -> Abbrev.term -> Abbrev.thm option

Admittedly, the existing documentation is not great, but sufficient for most purposes, I believe. Documenting it in much more detail would require me to read up on this stuff in detail again and get very familiar with temporal logics again, which I have not done anything with since 12 years as well. I'm not willing to spend this amount of time.

**Comment by binghe** [comment]
Thanks. I should really try to find "documents" in ML's `.sig` files.

**Pull request merged**
